"""Stage-specific evidence modelling without experimental feasibility claims."""

from synthaudit.models.evaluation import (
    evaluate_evidence_scores,
    evaluate_predictions,
    run_feature_group_ablations,
)
from synthaudit.models.evidence import (
    AblationResultV1,
    AbstentionPolicyV1,
    CalibrationMethod,
    CalibrationSliceV1,
    EstimatorFamily,
    EvidenceEvaluationV1,
    EvidenceExampleSplit,
    EvidenceExampleV1,
    EvidenceFeatureV1,
    EvidenceModelManifestV1,
    EvidenceModelPlanV1,
    EvidenceModelRole,
    EvidencePredictionV1,
    EvidenceStage,
    EvidenceStagePlanV1,
    FeatureGroup,
    FeatureSchemaV1,
    ProviderDisagreementV1,
    ReliabilityBinV1,
    TransparentBaselineResultV1,
)
from synthaudit.models.extraction import extract_reaction_evidence_features
from synthaudit.models.features import (
    PLAUSIBILITY_GROUPS,
    EncodedEvidenceMatrix,
    EvidenceFeatureEncoder,
    feature_groups_for_role,
)
from synthaudit.models.training import (
    ScoredEvidenceBatch,
    TrainedEvidenceModel,
    fit_evidence_model,
    transparent_baseline,
)
from synthaudit.models.uncertainty import (
    BootstrapEvidenceEnsemble,
    fit_abstention_policy_from_calibration,
    fit_bootstrap_ensemble,
    predict_with_uncertainty,
    provider_disagreement,
)

__all__ = [
    "PLAUSIBILITY_GROUPS",
    "AblationResultV1",
    "AbstentionPolicyV1",
    "BootstrapEvidenceEnsemble",
    "CalibrationMethod",
    "CalibrationSliceV1",
    "EncodedEvidenceMatrix",
    "EstimatorFamily",
    "EvidenceEvaluationV1",
    "EvidenceExampleSplit",
    "EvidenceExampleV1",
    "EvidenceFeatureEncoder",
    "EvidenceFeatureV1",
    "EvidenceModelManifestV1",
    "EvidenceModelPlanV1",
    "EvidenceModelRole",
    "EvidencePredictionV1",
    "EvidenceStage",
    "EvidenceStagePlanV1",
    "FeatureGroup",
    "FeatureSchemaV1",
    "ProviderDisagreementV1",
    "ReliabilityBinV1",
    "ScoredEvidenceBatch",
    "TrainedEvidenceModel",
    "TransparentBaselineResultV1",
    "evaluate_evidence_scores",
    "evaluate_predictions",
    "extract_reaction_evidence_features",
    "feature_groups_for_role",
    "fit_abstention_policy_from_calibration",
    "fit_bootstrap_ensemble",
    "fit_evidence_model",
    "predict_with_uncertainty",
    "provider_disagreement",
    "run_feature_group_ablations",
    "transparent_baseline",
]
